//! Builds the grammar dump `vigia-core` embeds, and the attribution beside it.
//!
//! `SPEC.md` §6 rules the mechanism: `two-face`'s `fancy`-vetted packaging of
//! `bat`'s curated grammar set is the base, the `.sublime-syntax` files under
//! `assets/syntaxes/` are the locally vendored extras, and the two merge into
//! one dump at `crates/vigia-core/assets/syntaxes.bin`, which is committed so
//! that neither CI nor `cargo publish` ever needs a grammar source.
//!
//! Run it from anywhere in the workspace when the grammar set changes:
//!
//! ```sh
//! cargo run -p xtask
//! ```
//!
//! **Every local extra has its patterns force-compiled under the shipped
//! engine before it is admitted.** `syntect` compiles patterns lazily behind an
//! `expect`, the workspace builds with `panic = "abort"`, so a grammar carrying
//! one incompatible pattern is a process kill on the first file that reaches
//! it. `two-face`'s `fancy` build guarantees this property for its own set by
//! construction; the extras have nobody to guarantee it but us, and a lazy
//! compile is a gate that green-lights whatever nothing happened to reach.
//! `crates/vigia-core/tests/coverage.rs` holds the same check as a CI gate, so
//! a dump regenerated by hand cannot dodge it.
//!
//! Two more things this tool writes are what let that gate see a stale dump at
//! all. It refuses a vendored extra whose name is already in the set, from
//! `two-face` or from another extra, because `SyntaxSetBuilder::add` pushes
//! and every lookup runs newest-first, so a collision shadows silently. And
//! it writes two committed records beside the sources in the same run as the
//! dump: `NOTICE.md`'s Sources table, an FNV-1a 64 per vendored file, and
//! `GRAMMARS.txt`, the sorted name of every grammar in the dump. The gates
//! recompute both, which is what turns "somebody edited a grammar and forgot
//! to rebuild" from invisible into red.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use syntect::parsing::Regex;
use syntect::parsing::syntax_definition::{Pattern, SyntaxDefinition};

fn main() {
    // The workspace root, addressed from this crate's own manifest rather than
    // from the invoker's working directory, so `cargo run -p xtask` behaves the
    // same from the root and from a crate directory.
    let root = Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("xtask sits one level under the workspace root")
        .to_path_buf();

    let base = two_face::syntax::extra_newlines();
    let base_count = base.syntaxes().len();

    let extras = load_extras(&root.join("assets").join("syntaxes"));
    let extra_names: Vec<String> = extras.iter().map(|d| d.name.clone()).collect();

    // A vendored extra whose name collides with a base grammar would shadow
    // it silently: `SyntaxSetBuilder::add` just pushes, and every by-name and
    // by-extension lookup iterates newest-first. The pin gate would go red on
    // nothing (the count is unchanged by a shadow), so the refusal lives
    // here, where the collision is created.
    // Two extras naming themselves the same thing shadow each other exactly
    // the same way, which is why they go into the one set rather than being
    // checked only against the base.
    {
        let mut names: std::collections::HashSet<&str> =
            base.syntaxes().iter().map(|s| s.name.as_str()).collect();
        for name in &extra_names {
            assert!(
                names.insert(name.as_str()),
                "vendored extra {name:?} shadows a grammar already in the set,                  whether from two-face or from another vendored file; rename                  it or drop it"
            );
        }
    }

    // The base is rewritten **before** the extras go in, so the collision
    // refusal above still sees exactly the set it was written against and the
    // rewrite can never touch a vendored file.
    let mut builder = guard_markdown_tables(base.into_builder());
    for def in extras {
        builder.add(def);
    }
    let set = builder.build();

    // Uncompressed, and that is a measured decision rather than a default:
    // the compressed form of this set costs 9.67ms to load in release (flate2
    // then bincode) where the uncompressed one costs 0.674ms, and two-face
    // ships its own dumps uncompressed for exactly this reason. The price is
    // binary size, which is the cheaper budget here by an order of magnitude.
    // Written straight to its destination; syntect has no uncompressed-to-Vec
    // spelling, and a temp-file roundtrip added nothing but a stale file on
    // panic.
    let dump_path = root
        .join("crates")
        .join("vigia-core")
        .join("assets")
        .join("syntaxes.bin");
    std::fs::create_dir_all(dump_path.parent().expect("the dump has a parent"))
        .expect("the dump's directory exists");
    syntect::dumps::dump_to_uncompressed_file(&set, &dump_path).expect("write the dump");
    let dump_len = std::fs::metadata(&dump_path).expect("stat the dump").len();

    write_notice(
        dump_path.parent().expect("the dump has a parent"),
        &root.join("assets").join("syntaxes"),
        &extra_names,
    );

    let mut names: Vec<&str> = set.syntaxes().iter().map(|s| s.name.as_str()).collect();
    names.sort_unstable();

    // **The roster, committed.** A count pin plus a hand-written allow-list
    // protects the grammars somebody thought to name and nothing else: an
    // upgrade that swaps one grammar for another leaves the count identical
    // and every named row present. This is the whole set, sorted, in a file
    // git diffs, so any addition, removal or rename shows up in review as
    // itself rather than as a number moving.
    // Beside the dump rather than beside the sources, and that is not
    // filing: `vigia-core` publishes its own test suite, so the gate that
    // reads this roster ships to consumers, and a file outside the package
    // directory is one that `include_str!` cannot find there. It describes
    // the dump, so it belongs where the dump is.
    let roster = dump_path.with_file_name("GRAMMARS.txt");
    let listing = format!("{}\n", names.join("\n"));
    std::fs::write(&roster, listing).expect("write the roster");
    println!(
        "{} syntaxes ({} from two-face {}, {} local), {} bytes uncompressed -> {}",
        set.syntaxes().len(),
        base_count,
        two_face_version(&root),
        extra_names.len(),
        dump_len,
        dump_path.display(),
    );
    for name in names {
        println!("  {name}");
    }
}

/// The two alternatives of Markdown's block-start lookahead that test for a
/// table row, and the guard inserted before each.
///
/// Both alternatives require a literal `|`, so a line without one can never
/// match either. The engine does not know that: it explores every parse of the
/// embedded inline-content alternation first, which embeds the code-span
/// pattern about twelve times, and only then concludes "no match". Cost is
/// roughly 4x per code span on the line, plateauing near 14.6ms where
/// `fancy-regex`'s 1,000,000 backtrack limit cuts it off. Measured against this
/// repository's own prose, a worst 24-line screenful of `ROADMAP.md` cost
/// **229.48ms against I9's 16ms budget**, fully warm, on every frame that
/// redrew it.
///
/// The guard is a zero-width lookahead for a pipe anywhere on the line, which
/// makes the impossible case fail in constant time and leaves every possible
/// case to the pattern that always handled it.
///
/// **Both, not one.** Alternation binds loosest, so a single guard after the
/// group opening covers only the first branch and buys nothing: tried, and
/// measured at 13.56ms against 12.995ms, which is no change at all.
const GUARD: &str = r"(?=[^|\n]*\|)";

/// The two alternatives, each paired with itself-plus-[`GUARD`].
const TABLE_ANCHORS: [(&str, &str); 2] = [
    (
        "|    (?x:\n    (?:(?x:",
        "|    (?x:\n    (?=[^|\\n]*\\|)(?:(?x:",
    ),
    (r"|   (?!\s+\|)(?x:", r"|   (?=[^|\n]*\|)(?!\s+\|)(?x:"),
];

/// Insert a pipe-presence guard into Markdown's table-detection lookahead.
///
/// `SPEC.md` §6 rules that the dump is `two-face`'s set plus local extras. This
/// is the one place that ruling is *not* a pure merge, so it is named there
/// too: a reader diffing our dump against `two-face`'s finds one pattern that
/// differs, and this is the explanation.
///
/// **It is a performance rewrite and not a semantic one.** Nothing here may
/// change what the grammar matches, only how fast it declines to match.
/// **Two checks hold that line and neither is sufficient alone.**
/// `crates/vigia-core/tests/coverage.rs::the_guarded_grammar_highlights_identically`
/// reconstructs the unguarded pattern from the shipped dump and asserts the full
/// `(offset, ScopeStackOp)` stream is identical across a corpus, which proves the
/// guard inert **relative to the dump that ships**. Because its control is
/// derived from that same artefact, any further change this function made would
/// sit in both of its arms and compare equal. The insertion-only assertion below
/// is what closes that: it pins the guarded pattern to the upstream string while
/// that string is still in hand, which is only possible here.
///
/// # Panics
///
/// If the number of patterns rewritten is not exactly one. A `two-face` bump
/// that renames the grammar, reflows the pattern or splits the alternation
/// would otherwise leave this silently doing nothing, and the only symptom
/// would be a budget gate going red a phase later with no clue attached. The
/// count is the whole gate here: it fails on the upgrade rather than on the
/// reader.
fn guard_markdown_tables(
    old: syntect::parsing::SyntaxSetBuilder,
) -> syntect::parsing::SyntaxSetBuilder {
    let mut rewritten = 0;
    let mut fresh = syntect::parsing::SyntaxSetBuilder::new();
    for def in old.syntaxes() {
        // `syntaxes()` hands back a slice rather than ownership, so the walk
        // is over clones and the result goes into a fresh builder. There is no
        // in-place spelling for this in syntect 5.3.
        let mut def = def.clone();
        for context in def.contexts.values_mut() {
            for pattern in context.patterns.iter_mut() {
                if let Pattern::Match(m) = pattern {
                    let regex = m.regex.regex_str();
                    // Both anchors, not either: the `table` context carries a
                    // pattern holding only the second one, and rewriting that
                    // would be a second, unmeasured change riding along with
                    // this one.
                    //
                    // **And leaving it costs nothing, which is measured rather
                    // than assumed.** That copy is only reachable from inside a
                    // table, so it cannot fire for the pipe-free prose #261 is
                    // about. Twelve one-line paragraphs cost 0.682ms alone and
                    // 0.718ms placed directly after a table, and a 24-row table
                    // carrying inline code and bold costs 0.526ms: the context
                    // does not leak into the lines that follow it, and a
                    // table-heavy screenful is nowhere near the 16ms budget.
                    if TABLE_ANCHORS.iter().all(|(from, _)| regex.contains(from)) {
                        let guarded = TABLE_ANCHORS
                            .iter()
                            .fold(regex.to_string(), |acc, (from, to)| acc.replace(from, to));
                        // **The rewrite must be a pure insertion, and this is
                        // the only place that can prove it.** Each entry of
                        // TABLE_ANCHORS restates the whole anchor alongside the
                        // guard, so a mistranscribed replacement would alter the
                        // pattern in some further way and nothing downstream
                        // would notice: `coverage.rs` builds its control arm by
                        // deleting the guard from the *shipped* dump, so any
                        // other change the replacement made is present in both
                        // of its arms and compares equal. That gate proves the
                        // guard is inert against itself; this assertion is what
                        // makes it inert against `two-face`, by pinning the
                        // guarded form to the upstream string it came from while
                        // that string is still in hand.
                        assert_eq!(
                            guarded.replace(GUARD, ""),
                            regex,
                            "the table rewrite changed the pattern by more than \
                             inserting the guard, so it is not the performance-only \
                             edit SPEC.md section 6 rules it to be"
                        );
                        m.regex = Regex::new(guarded);
                        rewritten += 1;
                    }
                }
            }
        }
        fresh.add(def);
    }
    assert_eq!(
        rewritten, 1,
        "expected exactly one Markdown table lookahead to guard, rewrote {rewritten}; \
         a two-face upgrade has moved the pattern this rewrite anchors on, so the \
         anchors in TABLE_ANCHORS need re-deriving against the new grammar"
    );
    fresh
}

/// Load every `.sublime-syntax` under `dir`, refusing any whose patterns do
/// not all compile under the engine `vigia` ships.
///
/// The walk is flat and sorted: extras are single vendored files, not trees,
/// and a deterministic order keeps the dump reproducible byte for byte.
fn load_extras(dir: &Path) -> Vec<SyntaxDefinition> {
    // No extras directory is a legal state: the dump is then exactly
    // two-face's set, and [`source_files`] returns nothing for it.
    source_files(dir)
        .iter()
        .map(|path| {
            let text = std::fs::read_to_string(path).expect("read a vendored grammar");
            // The file stem as the fallback name: `name:` is optional in the
            // format (Sublime derives it from the filename), and a grammar
            // that loads as "Unnamed" is unfindable by every by-name rule.
            let stem = path.file_stem().and_then(|s| s.to_str());
            // `true` for lines-include-newline, matching the newlines variant
            // of the base set and the `\n` the highlighter appends per line.
            let def = SyntaxDefinition::load_from_str(&text, true, stem)
                .unwrap_or_else(|e| panic!("{} does not parse: {e}", path.display()));
            let bad = incompatible_patterns(&def);
            assert!(
                bad.is_empty(),
                "{} carries {} pattern(s) the shipped engine cannot compile, \
                 and one reached at runtime aborts the monitor:\n{}",
                path.display(),
                bad.len(),
                bad.join("\n"),
            );
            def
        })
        .collect()
}

/// Every regex of every context of `def` that the shipped engine refuses,
/// the `first_line_match` included: `find_syntax_by_first_line` compiles it
/// behind the same lazy `expect` as any match pattern.
fn incompatible_patterns(def: &SyntaxDefinition) -> Vec<String> {
    let mut bad = Vec::new();
    if let Some(flm) = &def.first_line_match
        && let Some(err) = Regex::try_compile(flm)
    {
        bad.push(format!("  first_line_match: /{flm}/ -> {err}"));
    }
    for (context_name, context) in &def.contexts {
        for pattern in &context.patterns {
            if let Pattern::Match(m) = pattern
                && let Some(err) = Regex::try_compile(m.regex.regex_str())
            {
                bad.push(format!(
                    "  {context_name}: /{}/ -> {err}",
                    m.regex.regex_str()
                ));
            }
        }
    }
    bad
}

/// Regenerate the grammar attribution: two-face's own acknowledgements for
/// everything the base set embeds, plus the roster of local extras, whose
/// provenance (upstream, commit, licence) each file carries in its header.
///
/// **Written beside the dump rather than beside the sources, because it has to
/// ship.** The dump embeds a few hundred third-party grammars, each under its
/// own licence, and for two releases the notice describing them existed only
/// in this repository: `cargo package` carries the package directory, so a
/// crates.io consumer got the grammars and none of the attribution, and so did
/// every release archive. `bat` and `two-face` both ship theirs with the
/// artefact. `sources` is where the vendored `.sublime-syntax` files are read
/// from; `dir` is where the notice lands.
fn write_notice(dir: &Path, sources: &Path, extra_names: &[String]) {
    let mut md = String::new();
    md.push_str("# Grammar attribution\n\n");
    md.push_str(
        "Generated by `cargo run -p xtask`. Do not edit by hand.\n\n\
         The embedded grammar dump has two sources. The base set comes from \
         [two-face](https://codeberg.org/CosmicHarper/two-face), which packages \
         [bat](https://github.com/sharkdp/bat)'s curated syntax collection; its \
         acknowledgements are reproduced in full below. The rest are vendored \
         into the vigia repository under `assets/syntaxes/`, and each carries \
         its own upstream, pinned commit and licence in a header comment.\n\n",
    );
    if !extra_names.is_empty() {
        md.push_str("## Local extras\n\n");
        md.push_str(
            "Grammars vendored into the vigia repository, each at a pinned \
             upstream commit. The provenance below is read out of the vendored \
             file's own header, so it cannot disagree with the file it \
             describes.\n\n",
        );
        for name in extra_names {
            let _ = writeln!(md, "- {name}");
        }
        md.push('\n');

        for path in &source_files(sources) {
            let text = std::fs::read_to_string(path).expect("re-read a vendored grammar");
            let name = path
                .file_name()
                .expect("a file has a name")
                .to_string_lossy();
            let _ = writeln!(md, "**`{name}`**\n");
            // The four header fields the vendoring convention writes. Anything
            // else in the header is the grammar's own comment and is left where
            // it is.
            for field in ["upstream", "pinned", "path", "licence"] {
                if let Some(value) = text.lines().find_map(|line| {
                    line.trim_start()
                        .strip_prefix('#')?
                        .trim_start()
                        .strip_prefix(&format!("{field}:"))
                        .map(str::trim)
                }) {
                    let _ = writeln!(md, "- {field}: {value}");
                }
            }
            md.push('\n');
        }

        // **Their licence texts, inlined.** A name is not attribution: MIT asks
        // for the copyright and permission notice in every copy of a
        // substantial portion, and Apache-2.0 asks for the notices and a copy
        // of the licence. The dump is a copy of these grammars, so the text has
        // to travel with it, and the header comments that carry it in the
        // vendored `.sublime-syntax` files live outside the package and reach
        // nobody who installs the crate.
        //
        // Only the upstreams `bat` does not carry need one here. `two-face`'s
        // own listing below reproduces a `LICENSE` per grammar for everything
        // in `bat`'s curation, PowerShell's included, so duplicating those
        // would be two copies to drift apart.
        let mut licences: Vec<_> = std::fs::read_dir(sources.join("licences"))
            .into_iter()
            .flatten()
            .filter_map(|e| e.ok())
            .map(|e| e.path())
            .filter(|p| p.extension().is_some_and(|e| e == "LICENSE"))
            .collect();
        licences.sort();
        if !licences.is_empty() {
            md.push_str(
                "Licences for the grammars vendored from upstreams outside \
                 `bat`'s curation. The rest, PowerShell included, are \
                 reproduced per grammar in the two-face acknowledgements \
                 below.\n\n",
            );
            for path in licences {
                let text = std::fs::read_to_string(&path).expect("read a vendored licence");
                let stem = path
                    .file_stem()
                    .expect("a file has a stem")
                    .to_string_lossy();
                let _ = writeln!(
                    md,
                    "<details>\n<summary>{stem}</summary>\n\n````text\n{}\n````\n\n</details>\n",
                    text.replace("\r\n", "\n").trim_end()
                );
            }
            md.push('\n');
        }

        // **What we changed, which both licences ask to be stated.** Two
        // grammars are modified, and this list is the shipped statement of it:
        // `NOTICE.md` travels in every release archive (SPEC.md section 6),
        // where `SPEC.md` itself does not, so a modification recorded only in
        // the spec is a modification the recipient never sees.
        //
        // **The Markdown row is a modification of a `two-face`/`bat` grammar
        // rather than of a file in this repository**, which is why it is easy
        // to forget: nothing under `assets/syntaxes/` changed for it, so the
        // per-file hash table below cannot mention it and the vendored-source
        // walk never reaches it.
        md.push_str(
            "### Modifications\n\n- `PowerShell.sublime-syntax`: one match \
             pattern rewritten, replacing a regex subroutine call the shipped \
             engine cannot compile with the class it referenced. The change is \
             marked in place, beside the pattern.\n- `Markdown.sublime-syntax` \
             (from the base set, not vendored here): one match pattern \
             rewritten. A zero-width guard, `(?=[^|\\n]*\\|)`, is inserted \
             before each of the two alternatives of the block-start \
             lookahead's table-row test. Both alternatives already require a \
             literal `|`, so the guard changes no match and only lets a line \
             without one fail in constant time instead of exploring the inline \
             alternation first. The rewrite is applied by `xtask`, which \
             asserts it is a pure insertion against the upstream string, and \
             the emitted scope stream is asserted identical in \
             `crates/vigia-core/tests/coverage.rs`.\n\n",
        );
        md.push_str(
            "## Sources\n\nFNV-1a 64 of each vendored source as compiled into \
             the dump. `tests/coverage.rs` recomputes these, which is what \
             catches a source edited without `cargo run -p xtask`: the dump \
             and this table regenerate together or not at all.\n\n",
        );
        for file in source_files(sources) {
            let bytes = std::fs::read(&file).expect("re-read a vendored grammar");
            let name = file
                .file_name()
                .expect("a file has a name")
                .to_string_lossy();
            let _ = writeln!(md, "- `{name}`: {:016x}", fnv1a64(&bytes));
        }
        md.push('\n');
    }
    md.push_str("## two-face acknowledgements\n\n");
    md.push_str(&two_face::acknowledgement::listing().to_md());

    std::fs::create_dir_all(dir).expect("the notice's directory exists");
    // Some upstream licence texts carry CRLF; normalised so a regeneration on
    // any platform produces the same bytes and a clean diff.
    std::fs::write(dir.join("NOTICE.md"), md.replace("\r\n", "\n")).expect("write NOTICE.md");
}

/// The vendored grammar sources under `dir`, sorted, so the notice's sections
/// and the dump itself are built from one enumeration rather than three.
fn source_files(dir: &Path) -> Vec<PathBuf> {
    let mut files: Vec<PathBuf> = std::fs::read_dir(dir)
        .into_iter()
        .flatten()
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| p.extension().is_some_and(|e| e == "sublime-syntax"))
        .collect();
    files.sort();
    files
}

/// FNV-1a 64, spelled out because the checksum must be identical between
/// this tool and `tests/coverage.rs` forever, which rules out
/// `DefaultHasher` (stable only within a compiler release). Duplicated there
/// for the same reason the pattern check is: the two crates cannot share
/// without a new workspace member.
fn fnv1a64(bytes: &[u8]) -> u64 {
    let mut hash = 0xcbf2_9ce4_8422_2325u64;
    for &b in bytes {
        hash ^= u64::from(b);
        hash = hash.wrapping_mul(0x0000_0100_0000_01b3);
    }
    hash
}

/// The exact two-face release the dump was generated from, read from the
/// workspace `Cargo.lock` rather than restated here, so a dependency bump
/// cannot leave this provenance line silently stale. The crate encodes the
/// bat release it tracks in its version.
fn two_face_version(root: &Path) -> String {
    let lock = std::fs::read_to_string(root.join("Cargo.lock")).expect("read Cargo.lock");
    lock.split("[[package]]")
        .find(|entry| entry.contains("name = \"two-face\""))
        .and_then(|entry| {
            entry
                .lines()
                .find_map(|line| line.trim().strip_prefix("version = "))
        })
        .map(|version| version.trim_matches('"').to_owned())
        .expect("two-face is in the lock file")
}
