//! Builds the grammar dump `vigia-core` embeds, and the attribution beside it.
//!
//! `SPEC.md` §6 rules the mechanism: `two-face`'s `fancy`-vetted packaging of
//! `bat`'s curated grammar set is the base, the `.sublime-syntax` files under
//! `assets/syntaxes/` are the locally vendored extras, and the two merge into
//! one dump at `crates/vigia-core/assets/syntaxes.bin`, which is committed so
//! that neither CI nor `cargo publish` ever needs a grammar source.
//!
//! Run it from anywhere in the workspace when the grammar set changes:
//!
//! ```sh
//! cargo run -p xtask
//! ```
//!
//! **Every local extra has its patterns force-compiled under the shipped
//! engine before it is admitted.** `syntect` compiles patterns lazily behind an
//! `expect`, the workspace builds with `panic = "abort"`, so a grammar carrying
//! one incompatible pattern is a process kill on the first file that reaches
//! it. `two-face`'s `fancy` build guarantees this property for its own set by
//! construction; the extras have nobody to guarantee it but us, and a lazy
//! compile is a gate that green-lights whatever nothing happened to reach.
//! `crates/vigia-core/tests/coverage.rs` holds the same check as a CI gate, so
//! a dump regenerated by hand cannot dodge it.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use syntect::parsing::Regex;
use syntect::parsing::syntax_definition::{Pattern, SyntaxDefinition};

fn main() {
    // The workspace root, addressed from this crate's own manifest rather than
    // from the invoker's working directory, so `cargo run -p xtask` behaves the
    // same from the root and from a crate directory.
    let root = Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("xtask sits one level under the workspace root")
        .to_path_buf();

    let base = two_face::syntax::extra_newlines();
    let base_count = base.syntaxes().len();

    let extras = load_extras(&root.join("assets").join("syntaxes"));
    let extra_names: Vec<String> = extras.iter().map(|d| d.name.clone()).collect();

    // A vendored extra whose name collides with a base grammar would shadow
    // it silently: `SyntaxSetBuilder::add` just pushes, and every by-name and
    // by-extension lookup iterates newest-first. The pin gate would go red on
    // nothing (the count is unchanged by a shadow), so the refusal lives
    // here, where the collision is created.
    // Two extras naming themselves the same thing shadow each other exactly
    // the same way, which is why they go into the one set rather than being
    // checked only against the base.
    {
        let mut names: std::collections::HashSet<&str> =
            base.syntaxes().iter().map(|s| s.name.as_str()).collect();
        for name in &extra_names {
            assert!(
                names.insert(name.as_str()),
                "vendored extra {name:?} shadows a grammar already in the set,                  whether from two-face or from another vendored file; rename                  it or drop it"
            );
        }
    }

    let mut builder = base.into_builder();
    for def in extras {
        builder.add(def);
    }
    let set = builder.build();

    // Uncompressed, and that is a measured decision rather than a default:
    // the compressed form of this set costs 9.67ms to load in release (flate2
    // then bincode) where the uncompressed one costs 0.674ms, and two-face
    // ships its own dumps uncompressed for exactly this reason. The price is
    // binary size, which is the cheaper budget here by an order of magnitude.
    // Written straight to its destination; syntect has no uncompressed-to-Vec
    // spelling, and a temp-file roundtrip added nothing but a stale file on
    // panic.
    let dump_path = root
        .join("crates")
        .join("vigia-core")
        .join("assets")
        .join("syntaxes.bin");
    std::fs::create_dir_all(dump_path.parent().expect("the dump has a parent"))
        .expect("the dump's directory exists");
    syntect::dumps::dump_to_uncompressed_file(&set, &dump_path).expect("write the dump");
    let dump_len = std::fs::metadata(&dump_path).expect("stat the dump").len();

    write_notice(&root.join("assets").join("syntaxes"), &extra_names);

    let mut names: Vec<&str> = set.syntaxes().iter().map(|s| s.name.as_str()).collect();
    names.sort_unstable();
    println!(
        "{} syntaxes ({} from two-face {}, {} local), {} bytes uncompressed -> {}",
        set.syntaxes().len(),
        base_count,
        two_face_version(&root),
        extra_names.len(),
        dump_len,
        dump_path.display(),
    );
    for name in names {
        println!("  {name}");
    }
}

/// Load every `.sublime-syntax` under `dir`, refusing any whose patterns do
/// not all compile under the engine `vigia` ships.
///
/// The walk is flat and sorted: extras are single vendored files, not trees,
/// and a deterministic order keeps the dump reproducible byte for byte.
fn load_extras(dir: &Path) -> Vec<SyntaxDefinition> {
    let mut files: Vec<PathBuf> = match std::fs::read_dir(dir) {
        Ok(entries) => entries
            .filter_map(|e| e.ok())
            .map(|e| e.path())
            .filter(|p| p.extension().is_some_and(|e| e == "sublime-syntax"))
            .collect(),
        // No extras directory is a legal state: the dump is then exactly
        // two-face's set.
        Err(_) => return Vec::new(),
    };
    files.sort();

    files
        .iter()
        .map(|path| {
            let text = std::fs::read_to_string(path).expect("read a vendored grammar");
            // The file stem as the fallback name: `name:` is optional in the
            // format (Sublime derives it from the filename), and a grammar
            // that loads as "Unnamed" is unfindable by every by-name rule.
            let stem = path.file_stem().and_then(|s| s.to_str());
            // `true` for lines-include-newline, matching the newlines variant
            // of the base set and the `\n` the highlighter appends per line.
            let def = SyntaxDefinition::load_from_str(&text, true, stem)
                .unwrap_or_else(|e| panic!("{} does not parse: {e}", path.display()));
            let bad = incompatible_patterns(&def);
            assert!(
                bad.is_empty(),
                "{} carries {} pattern(s) the shipped engine cannot compile, \
                 and one reached at runtime aborts the monitor:\n{}",
                path.display(),
                bad.len(),
                bad.join("\n"),
            );
            def
        })
        .collect()
}

/// Every regex of every context of `def` that the shipped engine refuses,
/// the `first_line_match` included: `find_syntax_by_first_line` compiles it
/// behind the same lazy `expect` as any match pattern.
fn incompatible_patterns(def: &SyntaxDefinition) -> Vec<String> {
    let mut bad = Vec::new();
    if let Some(flm) = &def.first_line_match
        && let Some(err) = Regex::try_compile(flm)
    {
        bad.push(format!("  first_line_match: /{flm}/ -> {err}"));
    }
    for (context_name, context) in &def.contexts {
        for pattern in &context.patterns {
            if let Pattern::Match(m) = pattern
                && let Some(err) = Regex::try_compile(m.regex.regex_str())
            {
                bad.push(format!(
                    "  {context_name}: /{}/ -> {err}",
                    m.regex.regex_str()
                ));
            }
        }
    }
    bad
}

/// Regenerate `assets/syntaxes/NOTICE.md`: two-face's own acknowledgements for
/// everything the base set embeds, plus the roster of local extras, whose
/// provenance (upstream, commit, licence) each file carries in its header.
fn write_notice(dir: &Path, extra_names: &[String]) {
    let mut md = String::new();
    md.push_str("# Grammar attribution\n\n");
    md.push_str(
        "Generated by `cargo run -p xtask`. Do not edit by hand.\n\n\
         The embedded grammar dump has two sources. The base set comes from \
         [two-face](https://github.com/CosmicHorrorDev/two-face), which packages \
         [bat](https://github.com/sharkdp/bat)'s curated syntax collection; its \
         acknowledgements are reproduced in full below. The files beside this \
         notice are locally vendored extras, and each carries its upstream, \
         pinned commit and licence in its own header comment.\n\n",
    );
    if !extra_names.is_empty() {
        md.push_str("## Local extras\n\n");
        for name in extra_names {
            let _ = writeln!(md, "- {name}");
        }
        md.push('\n');
        md.push_str(
            "## Sources\n\nFNV-1a 64 of each vendored source as compiled into \
             the dump. `tests/coverage.rs` recomputes these, which is what \
             catches a source edited without `cargo run -p xtask`: the dump \
             and this table regenerate together or not at all.\n\n",
        );
        let mut files: Vec<_> = std::fs::read_dir(dir)
            .expect("the extras directory exists when extras were loaded")
            .filter_map(|e| e.ok())
            .map(|e| e.path())
            .filter(|p| p.extension().is_some_and(|e| e == "sublime-syntax"))
            .collect();
        files.sort();
        for file in files {
            let bytes = std::fs::read(&file).expect("re-read a vendored grammar");
            let name = file
                .file_name()
                .expect("a file has a name")
                .to_string_lossy();
            let _ = writeln!(md, "- `{name}`: {:016x}", fnv1a64(&bytes));
        }
        md.push('\n');
    }
    md.push_str("## two-face acknowledgements\n\n");
    md.push_str(&two_face::acknowledgement::listing().to_md());

    std::fs::create_dir_all(dir).expect("assets/syntaxes exists");
    // Some upstream licence texts carry CRLF; normalised so a regeneration on
    // any platform produces the same bytes and a clean diff.
    std::fs::write(dir.join("NOTICE.md"), md.replace("\r\n", "\n")).expect("write NOTICE.md");
}

/// FNV-1a 64, spelled out because the checksum must be identical between
/// this tool and `tests/coverage.rs` forever, which rules out
/// `DefaultHasher` (stable only within a compiler release). Duplicated there
/// for the same reason the pattern check is: the two crates cannot share
/// without a new workspace member.
fn fnv1a64(bytes: &[u8]) -> u64 {
    let mut hash = 0xcbf2_9ce4_8422_2325u64;
    for &b in bytes {
        hash ^= u64::from(b);
        hash = hash.wrapping_mul(0x0000_0100_0000_01b3);
    }
    hash
}

/// The exact two-face release the dump was generated from, read from the
/// workspace `Cargo.lock` rather than restated here, so a dependency bump
/// cannot leave this provenance line silently stale. The crate encodes the
/// bat release it tracks in its version.
fn two_face_version(root: &Path) -> String {
    let lock = std::fs::read_to_string(root.join("Cargo.lock")).expect("read Cargo.lock");
    lock.split("[[package]]")
        .find(|entry| entry.contains("name = \"two-face\""))
        .and_then(|entry| {
            entry
                .lines()
                .find_map(|line| line.trim().strip_prefix("version = "))
        })
        .map(|version| version.trim_matches('"').to_owned())
        .expect("two-face is in the lock file")
}
