//! Builds the grammar dump `vigia-core` embeds, and the attribution beside it.
//!
//! `SPEC.md` §6 rules the mechanism: `two-face`'s `fancy`-vetted packaging of
//! `bat`'s curated grammar set is the base, the `.sublime-syntax` files under
//! `assets/syntaxes/` are the locally vendored extras, and the two merge into
//! one dump at `crates/vigia-core/assets/syntaxes.bin`, which is committed so
//! that neither CI nor `cargo publish` ever needs a grammar source.
//!
//! Run it from anywhere in the workspace when the grammar set changes:
//!
//! ```sh
//! cargo run -p xtask
//! ```
//!
//! **Every local extra has its patterns force-compiled under the shipped
//! engine before it is admitted.** `syntect` compiles patterns lazily behind an
//! `expect`, the workspace builds with `panic = "abort"`, so a grammar carrying
//! one incompatible pattern is a process kill on the first file that reaches
//! it. `two-face`'s `fancy` build guarantees this property for its own set by
//! construction; the extras have nobody to guarantee it but us, and a lazy
//! compile is a gate that green-lights whatever nothing happened to reach.
//! `crates/vigia-core/tests/coverage.rs` holds the same check as a CI gate, so
//! a dump regenerated by hand cannot dodge it.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use syntect::parsing::syntax_definition::{Pattern, SyntaxDefinition};
use syntect::parsing::Regex;

fn main() {
    // The workspace root, addressed from this crate's own manifest rather than
    // from the invoker's working directory, so `cargo run -p xtask` behaves the
    // same from the root and from a crate directory.
    let root = Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("xtask sits one level under the workspace root")
        .to_path_buf();

    let base = two_face::syntax::extra_newlines();
    let base_count = base.syntaxes().len();

    let extras = load_extras(&root.join("assets").join("syntaxes"));
    let extra_names: Vec<String> = extras.iter().map(|d| d.name.clone()).collect();

    let mut builder = base.into_builder();
    for def in extras {
        builder.add(def);
    }
    let set = builder.build();

    let dump = syntect::dumps::dump_binary(&set);
    let dump_path = root
        .join("crates")
        .join("vigia-core")
        .join("assets")
        .join("syntaxes.bin");
    std::fs::create_dir_all(dump_path.parent().expect("the dump has a parent"))
        .expect("the dump's directory exists");
    std::fs::write(&dump_path, &dump).expect("write the dump");

    write_notice(&root.join("assets").join("syntaxes"), &extra_names);

    let mut names: Vec<&str> = set.syntaxes().iter().map(|s| s.name.as_str()).collect();
    names.sort_unstable();
    println!(
        "{} syntaxes ({} from two-face {}, {} local), {} bytes compressed -> {}",
        set.syntaxes().len(),
        base_count,
        two_face_version(),
        extra_names.len(),
        dump.len(),
        dump_path.display(),
    );
    for name in names {
        println!("  {name}");
    }
}

/// Load every `.sublime-syntax` under `dir`, refusing any whose patterns do
/// not all compile under the engine `vigia` ships.
///
/// The walk is flat and sorted: extras are single vendored files, not trees,
/// and a deterministic order keeps the dump reproducible byte for byte.
fn load_extras(dir: &Path) -> Vec<SyntaxDefinition> {
    let mut files: Vec<PathBuf> = match std::fs::read_dir(dir) {
        Ok(entries) => entries
            .filter_map(|e| e.ok())
            .map(|e| e.path())
            .filter(|p| {
                p.extension().is_some_and(|e| e == "sublime-syntax")
            })
            .collect(),
        // No extras directory is a legal state: the dump is then exactly
        // two-face's set.
        Err(_) => return Vec::new(),
    };
    files.sort();

    files
        .iter()
        .map(|path| {
            let text = std::fs::read_to_string(path).expect("read a vendored grammar");
            // `true` for lines-include-newline, matching the newlines variant
            // of the base set and the `\n` the highlighter appends per line.
            let def = SyntaxDefinition::load_from_str(&text, true, None)
                .unwrap_or_else(|e| panic!("{} does not parse: {e}", path.display()));
            let bad = incompatible_patterns(&def);
            assert!(
                bad.is_empty(),
                "{} carries {} pattern(s) the shipped engine cannot compile, \
                 and one reached at runtime aborts the monitor:\n{}",
                path.display(),
                bad.len(),
                bad.join("\n"),
            );
            def
        })
        .collect()
}

/// Every regex of every context of `def` that the shipped engine refuses.
fn incompatible_patterns(def: &SyntaxDefinition) -> Vec<String> {
    let mut bad = Vec::new();
    for (context_name, context) in &def.contexts {
        for pattern in &context.patterns {
            if let Pattern::Match(m) = pattern
                && let Some(err) = Regex::try_compile(m.regex.regex_str())
            {
                bad.push(format!(
                    "  {context_name}: /{}/ -> {err}",
                    m.regex.regex_str()
                ));
            }
        }
    }
    bad
}

/// Regenerate `assets/syntaxes/NOTICE.md`: two-face's own acknowledgements for
/// everything the base set embeds, plus the roster of local extras, whose
/// provenance (upstream, commit, licence) each file carries in its header.
fn write_notice(dir: &Path, extra_names: &[String]) {
    let mut md = String::new();
    md.push_str("# Grammar attribution\n\n");
    md.push_str(
        "Generated by `cargo run -p xtask`. Do not edit by hand.\n\n\
         The embedded grammar dump has two sources. The base set comes from \
         [two-face](https://github.com/CosmicHorrorDev/two-face), which packages \
         [bat](https://github.com/sharkdp/bat)'s curated syntax collection; its \
         acknowledgements are reproduced in full below. The files beside this \
         notice are locally vendored extras, and each carries its upstream, \
         pinned commit and licence in its own header comment.\n\n",
    );
    if !extra_names.is_empty() {
        md.push_str("## Local extras\n\n");
        for name in extra_names {
            let _ = writeln!(md, "- {name}");
        }
        md.push('\n');
    }
    md.push_str("## two-face acknowledgements\n\n");
    md.push_str(&two_face::acknowledgement::listing().to_md());

    std::fs::create_dir_all(dir).expect("assets/syntaxes exists");
    // Some upstream licence texts carry CRLF; normalised so a regeneration on
    // any platform produces the same bytes and a clean diff.
    std::fs::write(dir.join("NOTICE.md"), md.replace("\r\n", "\n"))
        .expect("write NOTICE.md");
}

/// The exact two-face release the dump was generated from, for the line the
/// tool prints; the crate encodes the bat release it tracks in its version.
fn two_face_version() -> &'static str {
    "0.5.2+bat-0.26.1"
}
